version: '3.3'

services:
    db:
        image: mysql:8.0.22
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: recrafted
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
volumes:
    db_data: {}
